name: Run Ad Scraper

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: List files (debug)
        run: ls -la

      - name: Run scraper
        run: |
          python main.py
          cat sent_ads.txt  # Prikazuje sadržaj fajla za debug

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add sent_ads.txt
          git diff --cached --quiet || git commit -m "Update sent_ads.txt"
          git push
