name: Run Ad Scraper

on:
  schedule:
    - cron: "*/5 * * * *"  # Pokreće se svakih 5 minuta
  workflow_dispatch:  # Omogućava ručno pokretanje

jobs:
  scrape:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Neophodno za push promena

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Važno za git push

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run scraper
        run: python main.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add sent_ads.txt
          git diff --quiet && git diff --staged --quiet || git commit -m "Update sent_ads.txt"
          git push
